name = "v2raycloud"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "f1e242e5ec2f4285bb77f7d09372a659" }
]
